apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: seldon-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 8999 # kubeflow-gateway와 충돌 방지
      name: http
      protocol: HTTP
    hosts:
    - "*"
